# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Computational Design & Fabrication Group
email: your-email@example.com
description: The Computational Fabrication Group at the MIT Computer Science and Artificial Intelligence Laboratory investigates problems in digital manufacturing and computer graphics. The group is led by Professor Wojciech Matusik.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
# theme: minima
theme: cdfg-theme

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2


# Algolia search plugin
algolia:
  application_id: 'OMGVKMVLF3'
  index_name: 'MIT CSAIL CDFG'

# Pagination
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail:
    before: 2
    after: 2


# include collections in jekyll-feed plugin
feed:
  collections:
    - news
    - publications


permalink: /:title.html

collections_dir: collections
collections:
  courses:
  publications:
    output: true
    permalink: /:collection/:name
    sort_by: date
  research:
  news:
    output: true
    sort_by: date
    permalink: /:collection/:name
  team:

jekyll_admin:
  hidden_links:
    - posts

include:
  - "_assets/images"
# assets:
#   dirname: assets
#   sources:
#     - _assets/images
#     - _assets/files
#     - _assets/css

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git/
  - cdfg-theme/node_modules/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
