[[redirects]]
  from = "https://cdfg-website.netlify.app"
  to = "https://cdfg.mit.edu"
  status = 301
  force = true

[[redirects]]
  from = "https://cfg.mit.edu"
  to = "https://cdfg.mit.edu"
  status = 301
  force = true

[[redirects]]
  from = "https://cdfg.csail.mit.edu"
  to = "https://cdfg.mit.edu"
  status = 301
  force = true